# Generated by Django 4.1 on 2022-08-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name': '属(Genus)', 'verbose_name_plural': '属(Genus)'},
        ),
        migrations.AlterModelOptions(
            name='subfamily',
            options={'verbose_name': '亚科(Subfamily)', 'verbose_name_plural': '亚科(Subfamily)'},
        ),
        migrations.AlterField(
            model_name='basedata',
            name='antmap',
            field=models.URLField(blank=True, verbose_name='蚂蚁地图'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='antstore',
            field=models.URLField(blank=True, verbose_name='蚂蚁商店'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='antwiki',
            field=models.URLField(blank=True, verbose_name='蚂蚁维基'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='arena_humidity',
            field=models.CharField(blank=True, max_length=255, verbose_name='活动区湿度'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='arena_substrate',
            field=models.CharField(blank=True, max_length=255, verbose_name='活动区基底'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='arena_temperature',
            field=models.CharField(blank=True, max_length=255, verbose_name='活动区温度'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='camp_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='野外营巢'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='colony_form',
            field=models.CharField(blank=True, choices=[('monogyne', '单后形式'), ('polygyne', '多后形式')], max_length=255, verbose_name='群落形式'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='colony_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='群落规模'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='decoration',
            field=models.CharField(blank=True, max_length=255, verbose_name='活动区装饰'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='distribution',
            field=models.CharField(blank=True, max_length=255, verbose_name='分布'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='founding',
            field=models.CharField(blank=True, max_length=255, verbose_name='发育'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='habitat',
            field=models.CharField(blank=True, max_length=255, verbose_name='栖息地'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='hibernation',
            field=models.CharField(blank=True, max_length=255, verbose_name='冬眠'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='males_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='雄蚁颜色'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='males_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='雄蚁尺寸'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='mating_flight',
            field=models.CharField(blank=True, max_length=255, verbose_name='婚飞'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nest_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='巢形式'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nest_humidity',
            field=models.CharField(blank=True, max_length=255, verbose_name='巢湿度'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nest_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='巢尺寸'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nest_substrate',
            field=models.CharField(blank=True, max_length=255, verbose_name='巢基底'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nest_temperature',
            field=models.CharField(blank=True, max_length=255, verbose_name='巢温度'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='nutrition',
            field=models.CharField(blank=True, max_length=255, verbose_name='饲养食物'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='planting',
            field=models.CharField(blank=True, max_length=255, verbose_name='活动区种植'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='queen_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='蚁后颜色'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='queen_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='蚁后尺寸'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='soldier_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='兵蚁颜色'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='soldier_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='兵蚁尺寸'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='worker_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='工蚁颜色'),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='worker_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='工蚁尺寸'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='拉丁学名'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ant.subfamily', verbose_name='所属亚科'),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='name',
            field=models.CharField(max_length=255, verbose_name='拉丁学名'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='images/', verbose_name='文件名')),
                ('des', models.CharField(max_length=255, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('basedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ant.basedata', verbose_name='蚂蚁信息')),
            ],
        ),
    ]
